---
title: "PokeData"
output: html_document
runtime: html
---

```{r, echo=FALSE, message=FALSE}
# Tu
# setwd('C:/Users/Tu/Desktop/Sophomore Year/Spring/INFO 201/PokeData/assets/scripts')

source("./graphs.R")

popular.bar <- makeBar(1)
stacked.bar <- makeStacked()
stats.bar <- makeStats('Overall.Stats')
line.graph <- makeLine('avg.stats') 
pie <- makePie()
scatter <- makeScatter('weight', 'Health')
histogram <- makeHisto('height')

```
# Fun Pokemon Graphs! 

## What's the most **common** pokemon type of the first generation?

#### *Bar charts*

`r popular.bar`

> Surprisingly, poison type is the most common type of the first generation! Sadly, there are only 2 steel type Pokemon in the entire first gen. The bar chart graphs the number of pokemon for each type. Bar charts are used to show comparisons between categories of data through the length of the bars. One axis will generally consist of numerical values. For example, in this graph, the y axis represents the number of pokemon. The other axis will contain the types of categories being compared, in this case the different types of pokemon.

## What's the **strongest** type?

`r stats.bar`

> The almighty dragon type reigns supreme with an average overall base stats of 83. This base stats make them the strongest type in the game. Meanwhile, the lowly insects are the weakest since the average overall base stats of bug type is only 61. Once again, bar chart is used because it's easy to compare and contrast the quantity difference between different categories. 

## How's the number of Pokemon for each type **add up** over generations?

#### *Stacked Bar Chart*

`r stacked.bar`

> It's very interesting how even though poison got the lead with the most number of Pokemon in the first generation, their number stacked up so low when you combine all the data from all the generations together. The top 3 total Pokemon are water, normal, and flying. They all have consistent linear growth showcasing their commonality across all generations. The stacked bar chart displays the number of pokemon for each type and is categorized by the pokemon generation. Stacked bar chart is used to compare segments of a whole. Each bar in the chart represents a complete whole, and the split sections in the bar represent different categories of that whole. For example, in the displayed stacked bar chart, each bar represents the total number of pokemon for each type. The bar is split by the generation of the pokemon.


## How's the average base stats **change** over each generation?

#### *Line Chart*

`r line.graph`

> The jump in overall base stats between the 3rd generation and the 4th generation is one interesting finding. It shows that the newer Pokemon and especially the one from 4th generation are way stronger than before. The line chart displays the change in overall stats throughout each pokemon generation. Line charts are good for this kind of data because they are often used to compare the changes in a dataset over a course of a period.


## What's the most **common** color of Pokemon?

#### *Pie Chart*

`r pie`

> At first glance, it seems like there are a variety of colors of Pokemon in the game. It comes to no surprise that blue is the most common color considering how many water type Pokemon there are (take a look at the stacked bar chart). The pie chart displays the percentage of pokemon that represents a certain color. Pie charts are used to compare parts of a whole and do not show changes over time. For example, in our chart, each pokemon is categorized into a certain group of color, which will never change.

## What's the **relationship** between two different weight and health stat of Pokemon?

#### *Scatterplot*

`r scatter`

> The scatter plot displays the correlation between the weight and health of the pokemon. Scatter plots are used to show how much one variable is affected by another. The relationship between two variables is called their correlation. In this scatterplot we are determining how the weight of the pokemon may affect the health of the pokemon. Unsurprisingly, there is a positive correlation between the weight of the pokemon and its health stats. Bulkier and bigger Pokemon are usually harder to take down so this confirms it. 

## What's the **distribution** of stats in Pokemon?
#### *Histogram*

`r histogram`

> The histogram displays the the number of pokemon with a certain height. Histograms are used to show the frequency distribution (shape) of a continuous data. The six properties of a histogram are: bell-shaped, bimodal, skewed right, skewed left, uniform, and random. The histogram that is displayed in the Pokedex is heavily skewed right since it is positively skewed. In other words, there are a large number of occurrences on the left side and less occurrences on the right side. This occurs because the mean is greater than the median. These gigantic Pokemon that make up the outliers heavily affect and stretch out the chart. Most Pokemon are relatively normal size. 

